### ISSUE TITLE
MinimumIntervalS = 1800

### ISSUE THREAD

**Issue by fitzgeraldsteele** [brennentsmith/internet-speed-logger#13]
What is the reason for the 1800 sec (30min) minimum interval for the checks? Is there throttling somewhere on the speedtest API? Any reason why I couldn't set to, say 5 min intervals on my network?

**Comment by brennentsmith** [comment]
As the lead for the infrastructure team at Speedtest.net - I don't want my app stack hammered too hard? 😄 

More serious answer - the reason being is really a safety check. People often forget that the whole purpose of Speedtest is to *saturate* the internet connection, and we are good at it. The protocol is designed to be incredibly greedy, so unless active QOS is in place, it will impact other service performance. People also forget how much data this may burn through - on a high speed connection, you're going to potentially be moving terabytes per week. 

It's OSS - I can't stop you from forking and removing the check, but I highly recommend thinking about the potential impact to your connection if you test every 5 minutes.

**Comment by fitzgeraldsteele** [comment]
No, that makes sense. Thanks.

**Comment by jimthedj65** [comment]
this is great update, I just installed the logger and was wondering what the time frequency between tests was.  many thanks for a great app.
