### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by RyanGuyCode** [brennentsmith/internet-speed-logger#14]
I'm relatively new to dockers...I got this running, and it is beautiful and fast. Thanks! I have a few questions: 1, how is this upgraded when there is a new version? 2. I tried to move the compose.yml file into portainer as a stack to deploy and have better/easier management, but I find it doesn't get the config files as when its deployed the way you recommend from git ---- can this be done? Otherwise, it is great.

**Comment by brennentsmith** [comment]
Added documentation for upgrading to the latest version to the readme. I'm not an expert on Portainer, but you should be able to run this in any docker based setup based on the images.
