### ISSUE TITLE
Speedtest appears to be running in --single mode?

### ISSUE THREAD

**Issue by B3nihana** [brennentsmith/internet-speed-logger#19]
The results I'm seeing on the web interface seem a lot slower than other speedtest sites report. 

I can only reproduce the results in terminal when running "speedtest --single" but running "speedtest" gets me a download speed 3x higher and much closer to the advertised line speed.

It doesn't seem to be included in the variable, but wondered if it could be elsewhere or if other users have seen this behavior?

I have to say I'm very impressed with the tool and its exactly what I was looking for!

**Comment by jeffbyrnes** [comment]
I’m definitely getting results that line up with my advertised speed level. I’m also running it directly, without Docker. I was also trying out https://github.com/henrywhitaker3/Speedtest-Tracker via Docker, and that’s regularly giving me ⅓ my real speed as a result, so maybe it’s a Docker networking issue?

**Comment by brennentsmith** [comment]
I'm not able to reproduce this issue, this should be able to fully saturate your connection. @jeffbyrnes advice is good though, there is a possibility that Docker could interfere on high bandwidth connections. With that said, I'm running this personally in docker on a 1Gbit connection without issue.
