### ISSUE TITLE
Version in "./docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by alexcavazos67** [brennentsmith/internet-speed-logger#21]
docker-compose up shows
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Is there a way to run this without having to deal with containers?

**Comment by alexcavazos67** [comment]
.

**Comment by mcpeixoto** [comment]
How did you solved it?
