### ISSUE TITLE
Missing restart?

### ISSUE THREAD

**Issue by OzRocky** [brennentsmith/internet-speed-logger#22]
I'll preface this by saying that I'm not a Docker native. I might be missing something obvious. 

Is there a missing `restart: always` for mongo in `docker-compose.yml`? Until I added it, the logger wouldn't reload when my machine was rebooted.

r.

**Comment by brennentsmith** [comment]
Resolved here: https://github.com/brennentsmith/internet-speed-logger/commit/9e88257a981d0f8f751215b071f7b8c4243281d9
