### ISSUE TITLE
Docker installation fails

### ISSUE THREAD

**Issue by r-scotti** [brennentsmith/internet-speed-logger#33]
Hello.
I am not 'nerdy' enough to understand Dockers messages (see attachment)
Just to let you know: I did not succeed in installation.
Maybe some suggestions could help?
Many thanks, Roberto
[DockerLog.zip](https://github.com/brennentsmith/internet-speed-logger/files/7273180/DockerLog.zip)

**Comment by brennentsmith** [comment]
Dup of: https://github.com/brennentsmith/internet-speed-logger/issues/15

Solution, run at the root of the repo: `mkdir -p mongo-persistence && sudo chown -R 1001:1001 mongo-persistence`. Then everything should work.
