### ISSUE TITLE
Timezone change

### ISSUE THREAD

**Issue by cristiandiiorio** [brennentsmith/internet-speed-logger#43]
Is there a way to change the timezone? The time is an hour off for me.

**Comment by brennentsmith** [comment]
Hey @cristiandiiorio - I'd check the time on your server. Everything is recorded in UTC, and then normalized in the browser to the local timezone. If the server's timestamp is off, it'll record the time incorrectly.

**Comment by cristiandiiorio** [comment]
> Hey @cristiandiiorio - I'd check the time on your server. Everything is recorded in UTC, and then normalized in the browser to the local timezone. If the server's timestamp is off, it'll record the time incorrectly.

Yeah it fixed itself after some time but I forgot to close the issue. Nice application by the way!
