### ISSUE TITLE
Set speedtest server

### ISSUE THREAD

**Issue by timmay2** [brennentsmith/internet-speed-logger#7]
Hi. Not an issue as such but I'm wondering how I set the speedtest server to use. I had though that I just needed to edit nano internet-speed-logger/config/default.json

"...
    "commandString": "bin/speedtest -f json --accept-license --accept-gdpr",
..."

to
 
"...
    "commandString": "bin/speedtest --server 28236 -f json --accept-license --accept-gdpr",
..."

However this didn't work.

With default settings it seems to randomly select a server and not many are Gbps+ capable. Hence the need to manually set a server that is capable of multi Gbps.

**Comment by brennentsmith** [comment]
What error did you get timmay2? One key thing is that the server ID needs to be included in the list from `speedtest -L`.

**Comment by timmay2** [comment]
root@ubuntu-speedtest:~/internet-speed-logger/config# speedtest --server 28236 -f json --accept-license --accept-gdpr
usage: speedtest [-h] [--no-download] [--no-upload] [--single] [--bytes]
                 [--share] [--simple] [--csv] [--csv-delimiter CSV_DELIMITER]
                 [--csv-header] [--json] [--list] [--server SERVER]
                 [--exclude EXCLUDE] [--mini MINI] [--source SOURCE]
                 [--timeout TIMEOUT] [--secure] [--no-pre-allocate]
                 [--version]
speedtest: error: unrecognized arguments: -f json --accept-license --accept-gdpr

It seems that as soon as I add "--server 28236" to the command it is broken.

However, the command string on its own as-is from the config file doesn't run in the terminal.

Clearly I'm not understanding how you are running the speedtest command and can not just add "--server 28236" to specify the server to use.

**Comment by brennentsmith** [comment]
The correct flag to use is `--server-id` not `--server`

**Comment by timmay2** [comment]
Thanks!

Yes I was using the speedtest-cli version as a reference for the flags. I was not aware there was two versions.

All working now and set to a server that actually has capacity to test 1Gbps+ connections.

**Comment by brennentsmith** [comment]
Fantastic! Glad you got it working!
