### ISSUE TITLE
Changes in Config don't take effect.

### ISSUE THREAD

**Issue by Samuel-Potroz** [brennentsmith/internet-speed-logger#8]
Hello there.

Great piece of kit you've got here. Love it a lot. 

Only one problem. Changes in default.json under /config/default.json aren’t making any difference. As seen in this here image, I’ve set the speed test to run every hour. It’s been about 12 hours now since this config change went live, and It’s just completed another test (meaning it’s stuck on it’s default value) 

![image](https://user-images.githubusercontent.com/57206301/76587808-f83d3400-6549-11ea-921e-6a0c4520c8dd.png)
Also sidenote (if you have time), changes under /views/index.html aren't changing anything either. Tried to change the title from "speed logger" to something a little more descriptive for my use. 

Any ideas?

**Comment by brennentsmith** [comment]
Hey @Samuel-Potroz, I'm glad you like it!

How are you running the service? Are you using the docker-compose version, building your own containers, or running natively?

**Comment by Samuel-Potroz** [comment]
> Hey @Samuel-Potroz, I'm glad you like it!
> 
> How are you running the service? Are you using the docker-compose version, building your own containers, or running natively?

Hey there. I am using the docker-compose version. I found a fix for the issue and confimed it to be working just a few minutes ago. I copied the docker-compose.yml file from github and replaced the currently installed one, and it seems to have started respecting the configuration file. I'm not sure why this fixed it, as the files where identical.

**Comment by brennentsmith** [comment]
Glad to hear that you were able to get it figured out! Happy testing!
